### ISSUE TITLE
Set name and email from url params?

### ISSUE THREAD

**Issue by naoisegolden** [diglin/Diglin_Chat#8]
Hello. I was wondering if there is a way to automatically set the user's email and name from url params? 

Say I sent an email campaign, I know recipient's email and name, it should be possible for the zopim widget to get this info:

`<a href="https://myshop.com/promo/?zopim_name=Jane&zopim_email=jane@mail.com">`

And in the widget snippet:

``` js
  $zopim(function() {
    $zopim.livechat.setName(getURLParameter('zopim_name'));
    $zopim.livechat.setEmail(getURLParameter('zopim_email'));
  });
```

Or maybe there are better ways to achieve this same thing from a simple link?

**Comment by sylvainraye** [comment]
Hi,

Your concept should works. I mean, using `$zopim.livechat.setXYZ` will allow you to set such information on the fly. The extension already does that for logged in user. You have to check that you don't have issues with Magento cache  and conflict with existing `$zopim.livechat.setXYZ` which may be already inserted on the page while generating the widget.

**Comment by naoisegolden** [comment]
Hi @diglin thank you for your answer. My question is if the extension already does this or something similar? I know it works for logged in users, but haven't found anything similar to what I describe…

**Comment by sylvainraye** [comment]
Hi, no it doesn't but you can develop it.
